"""Bible HTML class names."""

BIBLE: str = "bible"
BLUE: str = "blue"
BOOK_INDEX: str = "book-index"
CHAPTER: str = "chapter"
COLLAPSE: str = "collapse"
COLLAPSIBLE: str = "collapsible"
INDEX_BOOK_CHAPTER_LIST: str = "index-book-chapter-list"
INDEX_BOOK_NAME: str = "index-book-name"
LANGUAGE: str = "language"
RED: str = "red"
RESULTS: str = "results"
TITLE: str = "title"
VERSE: str = "verse"
VERSE_GROUP: str = "verse-group"
VERSES: str = "verses"
