export const MAPPING: Record<string, string> = {
  Ge: 'genesis',
  Ex: 'exodus',
  Lev: 'leviticus',
  Nu: 'numbers',
  Deu: 'deuteronomy',
  Jos: 'joshua',
  Jud: 'judges',
  Ru: 'ruth',
  '1 Kg': 'first_samuel',
  '2 Kg': 'second_samuel',
  '3 Kg': 'first_kings',
  '4 Kg': 'second_kings',
  '1 Chr': 'first_chronicles',
  '2 Chr': 'second_chronicles',
  Est: 'esther',
  Jth: 'judith',
  Tob: 'tobit',
  '1 Mac': 'first_maccabees',
  '2 Mac': 'second_maccabees',
  Ps: 'psalms',
  Job: 'job',
  Pro: 'proverbs',
  Eccl: 'ecclesiastes',
  Cant: 'song_of_songs',
  Sa: 'wisdom_of_solomon',
  Si: 'wisdom_of_jesus_son_of_sirach',
  Is: 'isaiah',
  Jer: 'jeremiah',
  Lam: 'lamentations_of_jeremiah',
  Bar: 'baruch',
  EpJer: 'epistle_of_jeremiah',
  Ez: 'ezekiel',
  Dan: 'daniel',
  Hos: 'hosea',
  Am: 'amos',
  Mic: 'micah',
  Ob: 'obadiah',
  Jon: 'jonah',
  Nah: 'nahum',
  Hab: 'habakkuk',
  Zeph: 'zephaniah',
  Hag: 'haggai',
  Zech: 'zechariah',
  Mal: 'malachi',
  Mt: 'gospel_of_st__matthew',
  Mk: 'gospel_of_st__mark',
  Lu: 'gospel_of_st__luke',
  Jo: 'gospel_of_st__john',
  Ac: 'acts_of_the_apostles',
  Ro: 'epistle_to_the_romans',
  '1 Cor': 'first_epistle_to_the_corinthians',
  '2 Cor': 'second_epistle_to_the_corinthians',
  Gal: 'epistle_to_the_galatians',
  Eph: 'epistle_to_the_ephesians',
  Phil: 'epistle_to_the_philippians',
  Col: 'epistle_to_the_colossians',
  '1 Thes': 'first_epistle_to_the_thessalonians',
  '2 Thes': 'second_epistle_to_the_thessalonians',
  He: 'epistle_to_the_hebrews',
  '1 Tim': 'first_epistle_to_timothy',
  '2 Tim': 'second_epistle_to_timothy',
  Ti: 'epistle_to_titus',
  Ja: 'epistle_of_st__james',
  '1 Pet': 'first_epistle_of_st__peter',
  '2 Pet': 'second_epistle_of_st__peter',
  Ap: 'apocalypse',
};
