/** NOTE: This file is generated by the Bible pipeline. Do not
 * modify it manually!
 */

/** MAPPING maps a Crum Bible book abbreviation to book information.
 */
export const MAPPING: Record<
  string,
  {
    name: string;
    path: string;
    numChapters: number;
  }
> = {
  Ge: { name: 'Genesis', path: 'genesis', numChapters: 50 },
  Ex: { name: 'Exodus', path: 'exodus', numChapters: 40 },
  Lev: { name: 'Leviticus', path: 'leviticus', numChapters: 27 },
  Nu: { name: 'Numbers', path: 'numbers', numChapters: 36 },
  Num: { name: 'Numbers', path: 'numbers', numChapters: 36 },
  Deu: { name: 'Deuteronomy', path: 'deuteronomy', numChapters: 34 },
  Jos: { name: 'Joshua', path: 'joshua', numChapters: 24 },
  Jud: { name: 'Judges', path: 'judges', numChapters: 21 },
  Ru: { name: 'Ruth', path: 'ruth', numChapters: 4 },
  '1 Kg': { name: 'First Samuel', path: 'first_samuel', numChapters: 31 },
  '2 Kg': { name: 'Second Samuel', path: 'second_samuel', numChapters: 24 },
  '3 Kg': { name: 'First Kings', path: 'first_kings', numChapters: 4 },
  '4 Kg': { name: 'Second Kings', path: 'second_kings', numChapters: 1 },
  '1 Chr': {
    name: 'First Chronicles',
    path: 'first_chronicles',
    numChapters: 4,
  },
  '2 Chr': {
    name: 'Second Chronicles',
    path: 'second_chronicles',
    numChapters: 5,
  },
  Est: { name: 'Esther', path: 'esther', numChapters: 14 },
  Esth: { name: 'Esther', path: 'esther', numChapters: 14 },
  Jth: { name: 'Judith', path: 'judith', numChapters: 16 },
  Tob: { name: 'Tobit', path: 'tobit', numChapters: 14 },
  '1 Mac': { name: 'First Maccabees', path: 'first_maccabees', numChapters: 0 },
  '2 Mac': {
    name: 'Second Maccabees',
    path: 'second_maccabees',
    numChapters: 0,
  },
  Ps: { name: 'Psalms', path: 'psalms', numChapters: 152 },
  Job: { name: 'Job', path: 'job', numChapters: 42 },
  Pro: { name: 'Proverbs', path: 'proverbs', numChapters: 29 },
  Ecc: { name: 'Ecclesiastes', path: 'ecclesiastes', numChapters: 12 },
  Eccl: { name: 'Ecclesiastes', path: 'ecclesiastes', numChapters: 12 },
  Cant: { name: 'Song of Songs', path: 'song_of_songs', numChapters: 8 },
  Sa: { name: 'Wisdom of Solomon', path: 'wisdom_of_solomon', numChapters: 19 },
  Si: {
    name: 'Wisdom of Jesus son of Sirach',
    path: 'wisdom_of_jesus_son_of_sirach',
    numChapters: 51,
  },
  Is: { name: 'Isaiah', path: 'isaiah', numChapters: 66 },
  Jer: { name: 'Jeremiah', path: 'jeremiah', numChapters: 53 },
  Lam: {
    name: 'Lamentations of Jeremiah',
    path: 'lamentations_of_jeremiah',
    numChapters: 5,
  },
  Bar: { name: 'Baruch', path: 'baruch', numChapters: 5 },
  EpJer: {
    name: 'Epistle of Jeremiah',
    path: 'epistle_of_jeremiah',
    numChapters: 1,
  },
  Ez: { name: 'Ezekiel', path: 'ezekiel', numChapters: 48 },
  Dan: { name: 'Daniel', path: 'daniel', numChapters: 15 },
  Hos: { name: 'Hosea', path: 'hosea', numChapters: 14 },
  Am: { name: 'Amos', path: 'amos', numChapters: 9 },
  Mic: { name: 'Micah', path: 'micah', numChapters: 7 },
  Joel: { name: 'Joel', path: 'joel', numChapters: 3 },
  Ob: { name: 'Obadiah', path: 'obadiah', numChapters: 1 },
  Jon: { name: 'Jonah', path: 'jonah', numChapters: 4 },
  Nah: { name: 'Nahum', path: 'nahum', numChapters: 3 },
  Hab: { name: 'Habakkuk', path: 'habakkuk', numChapters: 3 },
  Zeph: { name: 'Zephaniah', path: 'zephaniah', numChapters: 3 },
  Hag: { name: 'Haggai', path: 'haggai', numChapters: 2 },
  Zach: { name: 'Zechariah', path: 'zechariah', numChapters: 14 },
  Zech: { name: 'Zechariah', path: 'zechariah', numChapters: 14 },
  Mal: { name: 'Malachi', path: 'malachi', numChapters: 4 },
  Mt: {
    name: 'Gospel of St. Matthew',
    path: 'gospel_of_st__matthew',
    numChapters: 28,
  },
  Mk: {
    name: 'Gospel of St. Mark',
    path: 'gospel_of_st__mark',
    numChapters: 16,
  },
  Lu: {
    name: 'Gospel of St. Luke',
    path: 'gospel_of_st__luke',
    numChapters: 24,
  },
  Jo: {
    name: 'Gospel of St. John',
    path: 'gospel_of_st__john',
    numChapters: 21,
  },
  Ac: {
    name: 'Acts of the Apostles',
    path: 'acts_of_the_apostles',
    numChapters: 28,
  },
  Ro: {
    name: 'Epistle to the Romans',
    path: 'epistle_to_the_romans',
    numChapters: 16,
  },
  '1 Cor': {
    name: 'First Epistle to the Corinthians',
    path: 'first_epistle_to_the_corinthians',
    numChapters: 16,
  },
  '2 Cor': {
    name: 'Second Epistle to the Corinthians',
    path: 'second_epistle_to_the_corinthians',
    numChapters: 13,
  },
  Gal: {
    name: 'Epistle to the Galatians',
    path: 'epistle_to_the_galatians',
    numChapters: 6,
  },
  Eph: {
    name: 'Epistle to the Ephesians',
    path: 'epistle_to_the_ephesians',
    numChapters: 6,
  },
  Phil: {
    name: 'Epistle to the Philippians',
    path: 'epistle_to_the_philippians',
    numChapters: 4,
  },
  Col: {
    name: 'Epistle to the Colossians',
    path: 'epistle_to_the_colossians',
    numChapters: 4,
  },
  '1 Thes': {
    name: 'First Epistle to the Thessalonians',
    path: 'first_epistle_to_the_thessalonians',
    numChapters: 5,
  },
  '2 Thes': {
    name: 'Second Epistle to the Thessalonians',
    path: 'second_epistle_to_the_thessalonians',
    numChapters: 3,
  },
  He: {
    name: 'Epistle to the Hebrews',
    path: 'epistle_to_the_hebrews',
    numChapters: 13,
  },
  '1 Tim': {
    name: 'First Epistle to Timothy',
    path: 'first_epistle_to_timothy',
    numChapters: 6,
  },
  '2 Tim': {
    name: 'Second Epistle to Timothy',
    path: 'second_epistle_to_timothy',
    numChapters: 4,
  },
  Ti: { name: 'Epistle to Titus', path: 'epistle_to_titus', numChapters: 3 },
  Tit: { name: 'Epistle to Titus', path: 'epistle_to_titus', numChapters: 3 },
  Philem: {
    name: 'Epistle to Philemon',
    path: 'epistle_to_philemon',
    numChapters: 1,
  },
  Ja: {
    name: 'Epistle of St. James',
    path: 'epistle_of_st__james',
    numChapters: 5,
  },
  '1 Pet': {
    name: 'First Epistle of St. Peter',
    path: 'first_epistle_of_st__peter',
    numChapters: 5,
  },
  '2 Pet': {
    name: 'Second Epistle of St. Peter',
    path: 'second_epistle_of_st__peter',
    numChapters: 3,
  },
  '1 Jo': {
    name: 'First Epistle of St. John',
    path: 'first_epistle_of_st__john',
    numChapters: 5,
  },
  '2 Jo': {
    name: 'Second Epistle of St. John',
    path: 'second_epistle_of_st__john',
    numChapters: 1,
  },
  '3 Jo': {
    name: 'Third Epistle of St. John',
    path: 'third_epistle_of_st__john',
    numChapters: 1,
  },
  Jude: {
    name: 'Epistle of St. Jude',
    path: 'epistle_of_st__jude',
    numChapters: 1,
  },
  Ap: { name: 'Apocalypse', path: 'apocalypse', numChapters: 22 },
  Apoc: { name: 'Apocalypse', path: 'apocalypse', numChapters: 22 },
};
